openapi: 3.0.3
info:
  title: todos-service
  version: '1.0'
  description: Сервис задач
servers:
  - url: 'http://localhost:3000'
tags:
  - name: news
    description: Новости
  - name: users
    description: Пользователи
  - name: tags
    description: Теги новостей
paths:
  /todos:
    post:
      summary: Создание задачи
      tags:
        - todo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Todo.yaml
      operationId: createTodo
      description: Создание задачи
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Todo.yaml
    get:
      summary: Получение списка задач
      tags:
        - todo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/dto/TodoList.yaml
      operationId: fetchTodos
  /news:
    get:
      summary: Получение списка новостей
      tags:
        - news
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/dto/NewsList.yaml
        '500':
          description: Internal Server Error
      operationId: fetchNews
      description: Получение списка новостей с пагинацией
    post:
      summary: Создание новой новости
      tags:
        - news
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../models/News.yaml
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: createNews
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/dto/CreateNews.yaml
      description: Создание новости
      security:
        - jwt: []
  '/news/{newsId}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: newsId
        in: path
        required: true
        description: ID новости
    get:
      summary: Получение новости по ID
      tags:
        - news
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/News.yaml
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: fetchNewsById
      description: Получение новости по ID
    patch:
      summary: Обновление полей записи
      tags:
        - news
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/News.yaml
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: updateNews
      description: Обновление новости
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/News.yaml
        description: Поля для обновления новости
    delete:
      summary: Удаление записи
      tags:
        - news
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: removeNews
      description: Удаление новости по ID
  /news/search:
    get:
      summary: Поиск новостей по критериям
      tags:
        - news
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/dto/NewsList.yaml
        '500':
          description: Internal Server Error
      operationId: searchNews
      description: Поиск новостей по параметрам
      parameters:
        - schema:
            type: string
          in: query
          name: title
          description: Заголовок новости
  /tags:
    get:
      summary: Получение списка всех тегов
      tags:
        - tags
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Tag.yaml
        '500':
          description: Internal Server Error
      operationId: fetchTags
      description: Получение списка всех тегов
    post:
      summary: Создание тега
      tags:
        - tags
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Tag.yaml
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: createTag
      description: Создание тега
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Tag.yaml
      security:
        - jwt: []
  '/tags/{tagId}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: tagId
        in: path
        required: true
        description: ID тега
    delete:
      summary: Удалить тег
      tags:
        - tags
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: removeTag
      description: Удаление тега по ID
      security:
        - jwt: []
  /users:
    get:
      summary: Список пользователей
      tags:
        - users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/dto/UsersList.yaml
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: fetchUsers
      description: Список пользователей
    post:
      summary: Создать пользователя
      tags:
        - users
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../models/User.yaml
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: createUser
      description: Создание пользователя
      security:
        - jwt: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/User.yaml
components:
  schemas: {}
  securitySchemes:
    jwt:
      name: Authorization
      type: apiKey
      in: header
x-stoplight:
  id: 4qqp6vkvdx7s7
x-json-schema-faker:
  locale: en
  min-items: 2
  max-items: 10
  optionalsProbability: 0.5
  resolve-json-path: true
